# Generated by Django 3.0.6 on 2020-05-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Not provided', max_length=200)),
                ('img_url', models.URLField(blank=True)),
                ('author', models.CharField(blank=True, default='Unknown', max_length=200)),
                ('prepare_time', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('cook_time', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('total_time', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('directions', models.TextField(blank=True, default='Unknown')),
                ('ingredients', models.ManyToManyField(related_name='recipes', to='recipe.Ingredient')),
            ],
        ),
    ]
