# Generated by Django 3.0.6 on 2020-05-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20200525_0845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
